#!/usr/bin/env bash

printf >>"${HOME}/.bashrc" "\nexport LOCAL=\${HOME}/.local\n"
printf >>"${HOME}/.bashrc" "export PATH=\${LOCAL}/bin:\${PATH}\n\n"
printf >>"${HOME}/.bashrc" "source <(scriptsort $LOCAL/scripts/shared --bundle)\n"
printf >>"${HOME}/.bashrc" "source <(scriptsort $LOCAL/scripts/bash --bundle)\n\n"
printf >>"${HOME}/.bashrc" "####### - Anything beyond this point is as of yet unmanaged - ########\n"
